"""Provider-neutral contracts and optional Gemini Scout adapter."""

from game_highlight_finder.providers.base import (
    MAX_USAGE_TOKENS_PER_DIMENSION,
    ProviderAdapter,
    ProviderCallResult,
    ProviderCapabilities,
    ProviderDescriptor,
    ProviderModel,
    ProviderRegistry,
    ProviderRequest,
    ProviderUsageActual,
    ProviderUsageEstimate,
)
from game_highlight_finder.providers.gemini import (
    GEMINI_MODEL_IDS,
    FakeGeminiTransport,
    GeminiCleanupError,
    GeminiConfigurationError,
    GeminiDispatchError,
    GeminiFailureDiagnostic,
    GeminiInteractionEnvelope,
    GeminiMissingUsageError,
    GeminiPrivacyError,
    GeminiProvider,
    GeminiProviderError,
    GeminiRemoteFile,
    GeminiTransport,
    GenAITransport,
    diagnose_gemini_exception,
    gemini_provider_descriptor,
)
from game_highlight_finder.providers.gemini_capabilities import (
    MODEL_DEFAULT_MINIMUM_THINKING,
    GeminiThinkingConfig,
    resolve_gemini_thinking_config,
)

__all__ = [
    "GEMINI_MODEL_IDS",
    "MAX_USAGE_TOKENS_PER_DIMENSION",
    "MODEL_DEFAULT_MINIMUM_THINKING",
    "FakeGeminiTransport",
    "GeminiCleanupError",
    "GeminiConfigurationError",
    "GeminiDispatchError",
    "GeminiFailureDiagnostic",
    "GeminiInteractionEnvelope",
    "GeminiMissingUsageError",
    "GeminiPrivacyError",
    "GeminiProvider",
    "GeminiProviderError",
    "GeminiRemoteFile",
    "GeminiThinkingConfig",
    "GeminiTransport",
    "GenAITransport",
    "ProviderAdapter",
    "ProviderCallResult",
    "ProviderCapabilities",
    "ProviderDescriptor",
    "ProviderModel",
    "ProviderRegistry",
    "ProviderRequest",
    "ProviderUsageActual",
    "ProviderUsageEstimate",
    "diagnose_gemini_exception",
    "gemini_provider_descriptor",
    "resolve_gemini_thinking_config",
]
