"""Provider-neutral contracts and optional Gemini Scout adapter."""

from game_highlight_finder.providers.base import (
    MAX_USAGE_TOKENS_PER_DIMENSION,
    ProviderAdapter,
    ProviderCallResult,
    ProviderCapabilities,
    ProviderDescriptor,
    ProviderModel,
    ProviderRegistry,
    ProviderRequest,
    ProviderUsageActual,
    ProviderUsageEstimate,
)
from game_highlight_finder.providers.gemini import (
    FakeGeminiTransport,
    GeminiCleanupError,
    GeminiConfigurationError,
    GeminiDispatchError,
    GeminiInteractionEnvelope,
    GeminiMissingUsageError,
    GeminiPrivacyError,
    GeminiProvider,
    GeminiProviderError,
    GeminiRemoteFile,
    GeminiTransport,
    GenAITransport,
    gemini_provider_descriptor,
)

__all__ = [
    "MAX_USAGE_TOKENS_PER_DIMENSION",
    "FakeGeminiTransport",
    "GeminiCleanupError",
    "GeminiConfigurationError",
    "GeminiDispatchError",
    "GeminiInteractionEnvelope",
    "GeminiMissingUsageError",
    "GeminiPrivacyError",
    "GeminiProvider",
    "GeminiProviderError",
    "GeminiRemoteFile",
    "GeminiTransport",
    "GenAITransport",
    "ProviderAdapter",
    "ProviderCallResult",
    "ProviderCapabilities",
    "ProviderDescriptor",
    "ProviderModel",
    "ProviderRegistry",
    "ProviderRequest",
    "ProviderUsageActual",
    "ProviderUsageEstimate",
    "gemini_provider_descriptor",
]
